version: '3.8'

services:
  frontend:
    build:
      context: ./path/to/frontend
    ports:
      - "3000:3000"
    environment:
      - EXPO_WEB_HOSTNAME=0.0.0.0

  backend:
    build:
      context: ./path/to/backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

