version: '3.8'

services:
  frontend:
    build:
      context: ./FRONT-END
      dockerfile: Dockerfile
    ports:
      - "3305:3305"
    networks:
      - app-network

  backend:
    build:
      context: ./BACK-END
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
